#! /bin/bash -e

user=`who | awk {'print $1'}`

chmod -R 775 /opt/RGCopy/
chown -R $user /opt/RGCopy/

cp /opt/RGCopy/copy_with_rgcopy /home/$user/.local/share/nautilus/scripts
#echo '(gtk_accel_path "<Actions>/ScriptsGroup/script_file:\\s\\s\\shome\\s'$user'\\s.gnome2\\snautilus-scripts\\scopy_with_rgcopy" "<Primary>v")' >> /home/$user/.gnome2/accels/nautilus
echo '(gtk_accel_path "<Actions>/ScriptsGroup/script_file:\\s\\s\\shome\\s'$user'\\s.local\\sshare\\snautilus\\sscripts\\scopy_with_rgcopy" "<Primary>v")' >> /home/reisy/.config/nautilus/accels
echo '(gtk_accel_path "<Actions>/DirViewActions/Paste" "")' >> /home/reisy/.config/nautilus/accels

chmod 777 /home/$user/.local/share/nautilus/scripts/copy_with_rgcopy
chown $user /home/$user/.local/share/nautilus/scripts/copy_with_rgcopy

su $user
nautilus -q

#apt-get install gvfs-fuse,gir1.2-appindicator3 Esto lo vamos a poner como dependencia
adduser $user fuse