#! /bin/bash -e

user=`who | grep tty | awk {'print $1'}`

chmod -R 775 /opt/rgcopy/
chown -R $user /opt/rgcopy/

cp /opt/rgcopy/copy_with_rgcopy /home/$user/.local/share/nautilus/scripts

echo '(gtk_accel_path "<Actions>/ScriptsGroup/script_file:\\s\\s\\shome\\s'$user'\\s.local\\sshare\\snautilus\\sscripts\\scopy_with_rgcopy" "<Primary>v")' >> /home/$user/.config/nautilus/accels

echo '(gtk_accel_path "<Actions>/DirViewActions/Paste" "")' >> /home/$user/.config/nautilus/accels

chmod  775  /home/$user/.local/share/nautilus/scripts/copy_with_rgcopy
chown  $user /home/$user/.local/share/nautilus/scripts/copy_with_rgcopy
#nautilus -q
